[package]
name = "arbide"
version = "0.1.0"
edition = "2021"
description = "Real-Time Arbitrage Detection System"
authors = ["Arbide"]
license = "MIT"

[dependencies]
rand = "0.8"
ctrlc = "3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
tokio-tungstenite = { version = "0.24", features = ["native-tls", "connect"] }
futures-util = "0.3"
serde_json = "1"